FROM node:0.12.6
WORKDIR /napp
RUN git clone --depth 1 https://github.com/bitpay/bitcore-node
RUN cd bitcore-node && npm --verbose --production install
ADD regnet.yml /napp/bitcore-node/config/
# NODE_ENV=regnet npm start
EXPOSE 8888
